Some fixes to robustify the addin
xunit/xamarinstudio.xunit pull request #52
Opened 2016-12-24 12:52 UTC by netonjm

Includes:
Bump MonoDevelop.Addins nuget to 0.3.8
Fixes NRE parsing unwanted data from shared libraries	
Adds multiple Inline test cases to the test tree	
Fixed wrong test tree recovered from file
Fixes wrong testCaseMethodAttributeMarker			
Fixes TestMarkers to work correctly with Fact and Theory markers

2017-01-03 08:03 UTC, lextm commented
Thanks. I would not be able to merge it till Xamarin/Mono fixes their build services.

2017-01-03 10:00 UTC, netonjm commented
There is a way to chat with you?

2017-01-03 10:11 UTC, lextm commented
@netonjm you can write mails to me support@lextm.com .

2017-01-12 13:43 UTC, lextm requested changes
Except one comment I left in https://github.com/xunit/xamarinstudio.xunit/pull/52/commits/e444e6cdd1828e993a35f14adb20140e37f7b67c I think all other changes look good.

If all code between #if EASY_DEBUGGING and #endif is kept, then I am happily accepting this PR.

2017-01-12 13:43 UTC, lextm commented on MonoDevelop.XUnit/XUnitTestLoader.cs
> -					using (var runner = new ExternalTestRunner()) {
I don't think we should remove the external test runner part.

2017-01-14 03:09 UTC, lextm approved these changes

2017-01-14 03:09 UTC, lextm commented
Never mind. I will merge it and then revise the change.

2017-01-14 03:09 UTC, merged